apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-service
  name: nginx-service
spec:
  ports:
  - name: 9000-80
    port: 9000
    protocol: TCP
    targetPort: 80
  selector:
    tier: backend
    deployment: app
  type: ClusterIP
status:
  loadBalancer: {}
