apiVersion: v1
kind: Service
metadata:
  name: kong-gw-proxy
  namespace: kong
spec:
  selector:
    app: kong-gw
  ports:
  - name: proxy
    port: 80
    targetPort: 8000
    protocol: TCP
    nodePort: 32000
  type: NodePort
