apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-gw
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong-gw
  template:
    metadata:
      labels:
        app: kong-gw
    spec:
      containers:
      - name: kong
        image: kong:latest
        env:
        - name: KONG_DATABASE
          value: "off"
        - name: KONG_PROXY_ACCESS_LOG
          value: /dev/stdout
        - name: KONG_ADMIN_ACCESS_LOG
          value: /dev/stdout
        - name: KONG_PROXY_ERROR_LOG
          value: /dev/stderr
        - name: KONG_ADMIN_ERROR_LOG
          value: /dev/stderr
        - name: KONG_ADMIN_LISTEN
          value: 0.0.0.0:8001
        - name: KONG_PROXY_LISTEN
          value: 0.0.0.0:8000
        - name: KONG_DECLARATIVE_CONFIG
          value: /kong/declarative/kong.yml
        volumeMounts:
        - name: config
          mountPath: /kong/declarative
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: kong-dbless-config
